#!/bin/bash


# Function to clean up Docker container
cleanup() {
    # Check if the Docker container is running
    if docker ps -a | grep -q "random-airnode"
    then
        echo "Cleaning up: Stopping and removing Docker container..."
        docker stop random-airnode &> /dev/null
        docker rm random-airnode &> /dev/null
    fi
}

# Trap exit signals to ensure cleanup
trap 'cleanup' EXIT

# Check if Docker is installed
if ! command -v docker
then
    echo "Error: Docker is not installed. Please install Docker before running this script."
    exit 1
fi

# Check if 'config.json' file exists in the current directory
if [ ! -f config.json ]
then
    echo "Error: 'config.json' file not found in the current directory."
    exit 1
fi

# Check if 'secrets.env' file exists in the current directory
if [ ! -f secrets.env ]
then
    echo "Error: 'secrets.env' file not found in the current directory."
    exit 1
fi

# Run Docker command in the background
docker run \
  --volume "$(pwd):/app/config" \
  --name random-airnode \
  --publish 3000:3000 \
  -d api3/airnode-client:latest

# Sanity check with curl to the specified endpoint
until curl -X POST -H 'Content-Type: application/json' -d '{"parameters": {"count": "5", "min": "1", "max": "6"}}' 'http://localhost:3000/http-data/01234567-abcd-abcd-abcd-012345678abc/0x6db9e3e3d073ad12b66d28dd85bcf49f58577270b1cc2d48a43c7025f5c27af6/' | grep -q "rawValue"
do 
    echo "Waiting for localhost:3000 to become available..."
    sleep 2
done

echo "Deploying AirnodeRrpV0.sol"

read -p "Enter private key: " private_key

# Run 'forge create' command with user input private key
echo forge create ./mock-contracts/src/AirnodeRrpV0.sol --private-key "$private_key"
forge create ./mock-contracts/AirnodeRrpV0.sol --private-key "$private_key"

# echo "RrpAddress: $rrp_address"